/* crypto/newhope/newhope_err.c */
/* ====================================================================
 * Copyright (c) 1999-2018 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/newhope.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_NEWHOPE,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_NEWHOPE,0,reason)

static ERR_STRING_DATA NEWHOPE_str_functs[] = {
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_COPY_A), "NEWHOPE_copy_a"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_FINISH), "NEWHOPE_finish"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_GEN_A_GS_AES), "NEWHOPE_gen_a_GS_AES"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_GEN_A_GS_SHA256), "NEWHOPE_gen_a_GS_SHA256"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_INITIATE), "NEWHOPE_initiate"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_NEW), "NEWHOPE_new"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_PKC_DEC), "NEWHOPE_PKC_dec"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_PKC_ENC), "NEWHOPE_PKC_enc"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_RESPOND), "NEWHOPE_respond"},
    {ERR_FUNC(NEWHOPE_F_NEWHOPE_SET_A_METHOD), "NEWHOPE_set_a_method"},
    {0, NULL}
};

static ERR_STRING_DATA NEWHOPE_str_reasons[] = {
    {ERR_REASON(NEWHOPE_R_512_HELP_REC), "512 help rec"},
    {ERR_REASON(NEWHOPE_R_BAD_AMETHOD), "bad amethod"},
    {ERR_REASON(NEWHOPE_R_BAD_KEYTYPE), "bad keytype"},
    {ERR_REASON(NEWHOPE_R_INVALID_SIZE), "invalid size"},
    {ERR_REASON(NEWHOPE_R_MISSING_A), "missing a"},
    {ERR_REASON(NEWHOPE_R_MISSING_KEY), "missing key"},
    {ERR_REASON(NEWHOPE_R_REQUIRES_KEYGEN), "requires keygen"},
    {ERR_REASON(NEWHOPE_R_SAMPLE_FAILURE), "sample failure"},
    {ERR_REASON(NEWHOPE_R_SIZE_MISMATCH), "size mismatch"},
    {ERR_REASON(NEWHOPE_R_VERIFICATION_FAILED), "verification failed"},
    {ERR_REASON(NEWHOPE_R_WRONG_ROLE), "wrong role"},
    {0, NULL}
};

#endif

void ERR_load_NEWHOPE_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(NEWHOPE_str_functs[0].error) == NULL) {
        ERR_load_strings(0, NEWHOPE_str_functs);
        ERR_load_strings(0, NEWHOPE_str_reasons);
    }
#endif
}
